# 1. Web Scraping

In [1]:
import requests # to send http requests
from bs4 import BeautifulSoup #to parse html
import pandas as pd
import numpy as np

In [14]:
pages = ["https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=0"]
for page in range(0,10000,60):
    pages.append("https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset="+str(page))

In [15]:
pages

['https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=0',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=0',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=60',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=120',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=180',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=240',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=300',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=360',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=420',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=480',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=540',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=600',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=660',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=720',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=780',
 'https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=840',

In [16]:
len(pages)

168

In [7]:
import cloudscraper
import time # For adding delay between requests to avoid rate limiting

In [24]:
from curl_cffi import requests
from bs4 import BeautifulSoup
import time

# Create a session that impersonates a real Chrome browser TLS fingerprint
session = requests.Session(impersonate="chrome120")

def getAndParseURL(url):
    headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://sofifa.com/",
        "Sec-Ch-Ua": '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": '"Windows"',
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "same-origin",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1"
    }
    
    try:
        response = session.get(url, headers=headers, timeout=10)
        
        if response.status_code != 200:
            print(f"HTTP Error {response.status_code} for URL: {url}")
            return None
            
        soup = BeautifulSoup(response.text, "html.parser")
        return soup
        
    except Exception as e:
        print(f"Request failed: {e}")
        return None


# Scraping Execution
players = []

for page in pages:
    print(f"Scraping: {page}")
    html = getAndParseURL(page)
    
    if html is None:
        continue

    # Locate the table container
    table = html.find("table") or html.select_one(".table")
    
    if table is not None:
        # Extract table headers once per page
        header_tr = table.find("tr")
        headers = [th.get_text().strip() for th in header_tr.find_all("th")] if header_tr else []

        # Parse player rows
        rows = table.find_all("tr")[1:]
        for row in rows:
            cols = row.find_all("td")
            if len(cols) > 1:
                player = {}
                player["name"] = cols[1].get_text().strip()
                
                for i in range(2, len(cols)):
                    if i < len(headers) and headers[i]:
                        player[headers[i]] = cols[i].get_text().strip()
                
                players.append(player)
    else:
        print(f"Table not found on page: {page}")
    
    time.sleep(2)  # Delay between requests to prevent rate-limiting

print(f"Finished! Scraped {len(players)} total players.")

Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=0
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=0
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=60
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=120
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=180
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=240
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=300
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=360
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=420
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=480
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=540
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=600
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=660
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=720
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=780
Scraping: https://sofifa.com/players?showCol%5B0%5D=pi&showCol%5B1%5D=ae&showCol%5B2%5D=hi&showCol%5B3%5D=wi&showCol%5B4%5D=pf&showCol%5B5%5D=oa&showCol%5B6%5D=pt&showCol%5B7%5D=bo&showCol%5B8%5D=bp&showCol%5B9%5D=gu&showCol%5B10%5D=vl&showCol%5B11%5D=wg&showCol%5B12%5D=rc&showCol%5B13%5D=ta&showCol%5B14%5D=cr&showCol%5B15%5D=fi&showCol%5B16%5D=he&showCol%5B17%5D=sh&showCol%5B18%5D=vo&showCol%5B19%5D=ts&showCol%5B20%5D=dr&showCol%5B21%5D=cu&showCol%5B22%5D=fr&showCol%5B23%5D=lo&showCol%5B24%5D=bl&showCol%5B25%5D=to&showCol%5B26%5D=ac&showCol%5B27%5D=sp&showCol%5B28%5D=ag&showCol%5B29%5D=re&showCol%5B30%5D=ba&showCol%5B31%5D=tp&showCol%5B32%5D=so&showCol%5B33%5D=ju&showCol%5B34%5D=st&showCol%5B35%5D=sr&showCol%5B36%5D=ln&showCol%5B37%5D=te&showCol%5B38%5D=ar&showCol%5B39%5D=in&showCol%5B40%5D=po&showCol%5B41%5D=vi&showCol%5B42%5D=pe&showCol%5B43%5D=cm&showCol%5B44%5D=td&showCol%5B45%5D=ma&showCol%5B46%5D=sa&showCol%5B47%5D=sl&showCol%5B48%5D=tg&showCol%5B49%5D=gd&showCol%5B50%5D=gh&showCol%5B51%5D=gc&showCol%5B52%5D=gp&showCol%5B53%5D=gr&showCol%5B54%5D=tt&showCol%5B55%5D=bs&showCol%5B56%5D=ir&showCol%5B57%5D=pac&showCol%5B58%5D=sho&showCol%5B59%5D=pas&showCol%5B60%5D=dri&showCol%5B61%5D=def&showCol%5B62%5D=phy%3D&offset=840

In [25]:
players

[{'name': 'M. Amondarain CM\nCDM',
  'Age': '20',
  'Overall rating': '72',
  'Potential': '81',
  'Team & Contract': 'Estudiantes de La Plata\n2025 ~ 2027',
  'ID': '74813',
  'Height': '185cm 6\'1"',
  'Weight': '75kg 165lbs',
  'foot': 'Right',
  'Best overall': '74',
  'Best position': 'CM',
  'Growth': '9',
  'Value': '€5M',
  'Wage': '€9K',
  'Release clause': '€8.5M',
  'Total attacking': '320',
  'Crossing': '66',
  'Finishing': '65',
  'Heading accuracy': '63',
  'Short passing': '75',
  'Volleys': '51',
  'Total skill': '325',
  'Dribbling': '72',
  'Curve': '55',
  'FK Accuracy': '51',
  'Long passing': '73',
  'Ball control': '74',
  'Total movement': '353',
  'Acceleration': '73',
  'Sprint speed': '74',
  'Agility': '71',
  'Reactions': '70',
  'Balance': '65',
  'Total power': '354',
  'Shot power': '67',
  'Jumping': '73',
  'Stamina': '80',
  'Strength': '67',
  'Long shots': '67',
  'Total mentality': '329',
  'Aggression': '73',
  'Interceptions': '69',
  'Attack position': '66',
  'Vision': '68',
  'Penalties': '53',
  'Composure': '72',
  'Total defending': '205',
  'Defensive awareness': '67',
  'Standing tackle': '69',
  'Sliding tackle': '69',
  'Total goalkeeping': '50',
  'GK Diving': '14',
  'GK Handling': '10',
  'GK Kicking': '7',
  'GK Positioning': '13',
  'GK Reflexes': '6',
  'Total stats': '1936',
  'Base stats': '420',
  'International reputation': '1',
  'Pace / Diving': '74',
  'Shooting / Handling': '65',
  'Passing / Kicking': '69',
  'Dribbling / Reflexes': '72',
  'Defending / Pace': '68'},
 {'name': 'C. Tzolis LM\nLW',
  'Age': '23',
  'Overall rating': '81',
  'Potential': '87',
  'Team & Contract': 'Club Brugge KV\n2024 ~ 2029',
  'ID': '256948',
  'Height': '179cm 5\'10"',
  'Weight': '73kg 161lbs',
  'foot': 'Right',
  'Best overall': '82',
  'Best position': 'CAM',
  'Growth': '6',
  'Value': '€40.5M',
  'Wage': '€36K',
  'Release clause': '€68.9M',
  'Total attacking': '378',
  'Crossing': '75',
  'Finishing': '80',
  'Heading accuracy': '68',
  'Short passing': '79',
  'Volleys': '76',
  'Total skill': '381',
  'Dribbling': '84',
  'Curve': '75',
  'FK Accuracy': '66',
  'Long passing': '75',
  'Ball control': '81',
  'Total movement': '410',
  'Acceleration': '85',
  'Sprint speed': '79',
  'Agility': '84',
  'Reactions': '77',
  'Balance': '85',
  'Total power': '382',
  'Shot power': '79',
  'Jumping': '78',
  'Stamina': '85',
  'Strength': '63',
  'Long shots': '77',
  'Total mentality': '324',
  'Aggression': '70',
  'Interceptions': '29',
  'Attack position': '79',
  'Vision': '78',
  'Penalties': '68',
  'Composure': '79',
  'Total defending': '110',
  'Defensive awareness': '33',
  'Standing tackle': '39',
  'Sliding tackle': '38',
  'Total goalkeeping': '53',
  'GK Diving': '15',
  'GK Handling': '10',
  'GK Kicking': '12',
  'GK Positioning': '6',
  'GK Reflexes': '10',
  'Total stats': '2038',
  'Base stats': '429',
  'International reputation': '1',
  'Pace / Diving': '82',
  'Shooting / Handling': '78',
  'Passing / Kicking': '77',
  'Dribbling / Reflexes': '83',
  'Defending / Pace': '38'},
 {'name': 'R. Ngumoha  LM\nLW',
  'Age': '16',
  'Overall rating': '72',
  'Potential': '88',
  'Team & Contract': 'Liverpool\n2025 ~ 2028',
  'ID': '80376',
  'Height': '170cm 5\'7"',
  'Weight': '68kg 150lbs',
  'foot': 'Right',
  'Best overall': '73',
  'Best position': 'CAM',
  'Growth': '16',
  'Value': '€6M',
  'Wage': '€29K',
  'Release clause': '€14.9M',
  'Total attacking': '293',
  'Crossing': '68',
  'Finishing': '66',
  'Heading accuracy': '38',
  'Short passing': '64',
  'Volleys': '57',
  'Total skill': '326',
  'Dribbling': '78',
  'Curve': '69',
  'FK Accuracy': '52',
  'Long passing': '53',
  'Ball control': '74',
  'Total movement': '419',
  'Acceleration': '92',
  'Sprint speed': '89',
  'Agility': '85',
  'Reactions': '65',
  'Balance': '88',
  'Total power': '314',
  'Shot power': '73',
  'Jumping': '61',
  'Stamina': '62',
  'Strength': '54',
  'Long shots': '64',
  'Total mentality': '271',
  'Aggression': '39',
  'Interceptions': '36',
  'Attack position': '66',
  'Vision': '71',
  'Penalties': '59',
  'Composure': '74',
  'Total defending': '101',
  'Defensive awareness': '32',
  'Standing tackle': '39',
  'Sliding tackle': '30',
  'Total goalkeeping': '49',
  'GK Diving': '11',
  'GK Handling': '9',
  'GK Kicking': '8',
  'GK Positioning': '9',
  'GK Reflexes': '12',
  'Total stats': '1773',
  'Base stats': '385',
  'International reputation': '1',
  'Pace / Diving': '90',
  'Shooting / Handling': '66',
  'Passing / Kicking': '64',
  'Dribbling / Reflexes': '77',
  'Defending / Pace': '35'},
 {'name': 'K. Adeyemi  RM\nLW\nCAM\nRW',
  'Age': '23',
  'Overall rating': '82',
  'Potential': '86',
  'Team & Contract': 'Borussia Dortmund\n2022 ~ 2027',
  'ID': '251852',
  'Height': '180cm 5\'11"',
  'Weight': '77kg 170lbs',
  'foot': 'Left',
  'Best overall': '84',
  'Best position': 'ST',
  'Growth': '4',
  'Value': '€43.5M',
  'Wage': '€52K',
  'Release clause': '€77.2M',
  'Total attacking': '374',
  'Crossing': '73',
  'Finishing': '81',
  'Heading accuracy': '75',
  'Short passing': '74',
  'Volleys': '71',
  'Total skill': '364',
  'Dribbling': '84',
  'Curve': '69',
  'FK Accuracy': '62',
  'Long passing': '69',
  'Ball control': '80',
  'Total movement': '441',
  'Acceleration': '96',
  'Sprint speed': '96',
  'Agility': '86',
  'Reactions': '82',
  'Balance': '81',
  'Total power': '399',
  'Shot power': '86',
  'Jumping': '93',
  'Stamina': '77',
  'Strength': '67',
  'Long shots': '76',
  'Total mentality': '316',
  'Aggression': '59',
  'Interceptions': '31',
  'Attack position': '82',
  'Vision': '74',
  'Penalties': '70',
  'Composure': '76',
  'Total defending': '108',
  'Defensive awareness': '25',
  'Standing tackle': '34',
  'Sliding tackle': '49',
  'Total goalkeeping': '50',
  'GK Diving': '12',
  'GK Handling': '12',
  'GK Kicking': '7',
  'GK Positioning': '12',
  'GK Reflexes': '7',
  'Total stats': '2052',
  'Base stats': '435',
  'International reputation': '3',
  'Pace / Diving': '96',
  'Shooting / Handling': '80',
  'Passing / Kicking': '72',
  'Dribbling / Reflexes': '82',
  'Defending / Pace': '36'},
 {'name': 'G. Mora CAM\nLW\nCM',
  'Age': '16',
  'Overall rating': '73',
  'Potential': '87',
  'Team & Contract': 'Mexico\nFree',
  'ID': '79399',
  'Height': '168cm 5\'6"',
  'Weight': '65kg 143lbs',
  'foot': 'Right',
  'Best overall': '75',
  'Best position': 'CAM',
  'Growth': '14',
  'Value': '€0',
  'Wage': '€0',
  'Release clause': '€0',
  'Total attacking': '321',
  'Crossing': '72',
  'Finishing': '68',
  'Heading accuracy': '48',
  'Short passing': '75',
  'Volleys': '58',
  'Total skill': '345',
  'Dribbling': '74',
  'Curve': '74',
  'FK Accuracy': '48',
  'Long passing': '72',
  'Ball control': '77',
  'Total movement': '348',
  'Acceleration': '68',
  'Sprint speed': '66',
  'Agility': '72',
  'Reactions': '72',
  'Balance': '70',
  'Total power': '274',
  'Shot power': '61',
  'Jumping': '50',
  'Stamina': '55',
  'Strength': '44',
  'Long shots': '64',
  'Total mentality': '300',
  'Aggression': '51',
  'Interceptions': '45',
  'Attack position': '74',
  'Vision': '77',
  'Penalties': '53',
  'Composure': '70',
  'Total defending': '157',
  'Defensive awareness': '44',
  'Standing tackle': '58',
  'Sliding tackle': '55',
  'Total goalkeeping': '46',
  'GK Diving': '11',
  'GK Handling': '12',
  'GK Kicking': '5',
  'GK Positioning': '9',
  'GK Reflexes': '9',
  'Total stats': '1791',
  'Base stats': '377',
  'International reputation': '1',
  'Pace / Diving': '67',
  'Shooting / Handling': '65',
  'Passing / Kicking': '73',
  'Dribbling / Reflexes': '74',
  'Defending / Pace': '50'},
 {'name': 'F. Mastantuono  RM\nRW',
  'Age': '17',
  'Overall rating': '77',
  'Potential': '87',
  'Team & Contract': 'Real Madrid\n2025 ~ 2031',
  'ID': '279173',
  'Height': '178cm 5\'10"',
  'Weight': '74kg 163lbs',
  'foot': 'Left',
  'Best overall': '79',
  'Best position': 'CAM',
  'Growth': '10',
  'Value': '€22M',
  'Wage': '€66K',
  'Release clause': '€49.5M',
  'Total attacking': '330',
  'Crossing': '72',
  'Finishing': '70',
  'Heading accuracy': '47',
  'Short passing': '76',
  'Volleys': '65',
  'Total skill': '381',
  'Dribbling': '81',
  'Curve': '74',
  'FK Accuracy': '74',
  'Long passing': '72',
  'Ball control': '80',
  'Total movement': '388',
  'Acceleration': '79',
  'Sprint speed': '73',
  'Agility': '82',
  'Reactions': '74',
  'Balance': '80',
  'Total power': '344',
  'Shot power': '73',
  'Jumping': '66',
  'Stamina': '73',
  'Strength': '60',
  'Long shots': '72',
  'Total mentality': '347',
  'Aggression': '70',
  'Interceptions': '53',
  'Attack position': '76',
  'Vision': '78',
  'Penalties': '70',
  'Composure': '78',
  'Total defending': '149',
  'Defensive awareness': '49',
  'Standing tackle': '51',
  'Sliding tackle': '49',
  'Total goalkeeping': '45',
  'GK Diving': '7',
  'GK Handling': '13',
  'GK Kicking': '10',
  'GK Positioning': '6',
  'GK Reflexes': '9',
  'Total stats': '1984',
  'Base stats': '418',
  'International reputation': '1',
  'Pace / Diving': '76',
  'Shooting / Handling': '71',
  'Passing / Kicking': '75',
  'Dribbling / Reflexes': '80',
  'Defending / Pace': '50'},
 {'name': 'M. Lacroix  CB',
  'Age': '25',
  'Overall rating': '81',
  'Potential': '83',
  'Team & Contract': 'Crystal Palace\n2024 ~ 2029',
  'ID': '244067',
  'Height': '190cm 6\'3"',
  'Weight': '89kg 196lbs',
  'foot': 'Right',
  'Best overall': '83',
  'Best position': 'CB',
  'Growth': '2',
  'Value': '€28.5M',
  'Wage': '€86K',
  'Release clause': '€56.3M',
  'Total attacking': '247',
  'Crossing': '35',
  'Finishing': '29',
  'Heading accuracy': '77',
  'Short passing': '71',
  'Volleys': '35',
  'Total skill': '279',
  'Dribbling': '66',
  'Curve': '45',
  'FK Accuracy': '26',
  'Long passing': '73',
  'Ball control': '69',
  'Total movement': '377',
  'Acceleration': '82',
  'Sprint speed': '93',
  'Agility': '64',
  'Reactions': '82',
  'Balance': '56',
  'Total power': '358',
  'Shot power': '75',
  'Jumping': '85',
  'Stamina': '77',
  'Strength': '84',
  'Long shots': '37',
  'Total mentality': '289',
  'Aggression': '81',
  'Interceptions': '83',
  'Attack position': '32',
  'Vision': '55',
  'Penalties': '38',
  'Composure': '75',
  'Total defending': '242',
  'Defensive awareness': '81',
  'Standing tackle': '82',
  'Sliding tackle': '79',
  'Total goalkeeping': '56',
  'GK Diving': '14',
  'GK Handling': '7',
  'GK Kicking': '12',
  'GK Positioning': '12',
  'GK Reflexes': '11',
  'Total stats': '1848',
  'Base stats': '416',
  'International reputation': '3',
  'Pace / Diving': '88',
  'Shooting / Handling': '41',
  'Passing / Kicking': '57',
  'Dribbling / Reflexes': '67',
  'Defending / Pace': '81'},
 {'name': 'L. Karl CAM\nRM\nST',
  'Age': '17',
  'Overall rating': '75',
  'Potential': '88',
  'Team & Contract': 'FC Bayern München\n2025 ~ 2028',
  'ID': '78063',
  'Height': '168cm 5\'6"',
  'Weight': '67kg 148lbs',
  'foot': 'Left',
  'Best overall': '77',
  'Best position': 'CAM',
  'Growth': '13',
  'Value': '€13M',
  'Wage': '€25K',
  'Release clause': '€29.6M',
  'Total attacking': '328',
  'Crossing': '69',
  'Finishing': '72',
  'Heading accuracy': '47',
  'Short passing': '74',
  'Volleys': '66',
  'Total skill': '355',
  'Dribbling': '83',
  'Curve': '76',
  'FK Accuracy': '54',
  'Long passing': '63',
  'Ball control': '79',
  'Total movement': '392',
  'Acceleration': '77',
  'Sprint speed': '68',
  'Agility': '84',
  'Reactions': '74',
  'Balance': '89',
  'Total power': '288',
  'Shot power': '68',
  'Jumping': '52',
  'Stamina': '55',
  'Strength': '34',
  'Long shots': '79',
  'Total mentality': '273',
  'Aggression': '33',
  'Interceptions': '34',
  'Attack position': '70',
  'Vision': '74',
  'Penalties': '62',
  'Composure': '69',
  'Total defending': '103',
  'Defensive awareness': '36',
  'Standing tackle': '32',
  'Sliding tackle': '35',
  'Total goalkeeping': '51',
  'GK Diving': '11',
  'GK Handling': '6',
  'GK Kicking': '8',
  'GK Positioning': '14',
  'GK Reflexes': '12',
  'Total stats': '1790',
  'Base stats': '370',
  'International reputation': '1',
  'Pace / Diving': '72',
  'Shooting / Handling': '72',
  'Passing / Kicking': '70',
  'Dribbling / Reflexes': '81',
  'Defending / Pace': '35'},
 {'name': 'Pau Cubarsí CB',
  'Age': '18',
  'Overall rating': '83',
  'Potential': '89',
  'Team & Contract': 'FC Barcelona\n2023 ~ 2029',
  'ID': '278046',
  'Height': '183cm 6\'0"',
  'Weight': '79kg 174lbs',
  'foot': 'Right',
  'Best overall': '86',
  'Best position': 'CB',
  'Growth': '6',
  'Value': '€48M',
  'Wage': '€70K',
  'Release clause': '€108M',
  'Total attacking': '282',
  'Crossing': '31',
  'Finishing': '41',
  'Heading accuracy': '83',
  'Short passing': '86',
  'Volleys': '41',
  'Total skill': '300',
  'Dribbling': '78',
  'Curve': '22',
  'FK Accuracy': '33',
  'Long passing': '85',
  'Ball control': '82',
  'Total movement': '365',
  'Acceleration': '72',
  'Sprint speed': '77',
  'Agility': '67',
  'Reactions': '83',
  'Balance': '66',
  'Total power': '330',
  'Shot power': '58',
  'Jumping': '87',
  'Stamina': '70',
  'Strength': '79',
  'Long shots': '36',
  'Total mentality': '333',
  'Aggression': '80',
  'Interceptions': '83',
  'Attack position': '54',
  'Vision': '75',
  'Penalties': '41',
  'Composure': '80',
  'Total defending': '251',
  'Defensive awareness': '84',
  'Standing tackle': '84',
  'Sliding tackle': '83',
  'Total goalkeeping': '51',
  'GK Diving': '10',
  'GK Handling': '6',
  'GK Kicking': '14',
  'GK Positioning': '7',
  'GK Reflexes': '14',
  'Total stats': '1912',
  'Base stats': '425',
  'International reputation': '3',
  'Pace / Diving': '75',
  'Shooting / Handling': '44',
  'Passing / Kicking': '67',
  'Dribbling / Reflexes': '78',
  'Defending / Pace': '84'},
 {'name': 'A. Bamba  CM\nCDM',
  'Age': '18',
  'Overall rating': '70',
  'Potential': '83',
  'Team & Contract': 'AS Monaco\n2025 ~ 2030',
  'ID': '75734',
  'Height': '194cm 6\'4"',
  'Weight': '80kg 176lbs',
  'foot': 'Right',
  'Best overall': '73',
  'Best position': 'CDM',
  'Growth': '13',
  'Value': '€3.7M',
  'Wage': '€11K',
  'Release clause': '€9.3M',
  'Total attacking': '291',
  'Crossing': '56',
  'Finishing': '51',
  'Heading accuracy': '62',
  'Short passing': '74',
  'Volleys': '48',
  'Total skill': '303',
  'Dribbling': '67',
  'Curve': '52',
  'FK Accuracy': '38',
  'Long passing': '72',
  'Ball control': '74',
  'Total movement': '295',
  'Acceleration': '59',
  'Sprint speed': '64',
  'Agility': '52',
  'Reactions': '72',
  'Balance': '48',
  'Total power': '350',
  'Shot power': '71',
  'Jumping': '74',
  'Stamina': '72',
  'Strength': '79',
  'Long shots': '54',
  'Total mentality': '310',
  'Aggression': '66',
  'Interceptions': '68',
  'Attack position': '62',
  'Vision': '70',
  'Penalties': '44',
  'Composure': '68',
  'Total defending': '201',
  'Defensive awareness': '66',
  'Standing tackle': '69',
  'Sliding tackle': '66',
  'Total goalkeeping': '56',
  'GK Diving': '12',
  'GK Handling': '12',
  'GK Kicking': '7',
  'GK Positioning': '11',
  'GK Reflexes': '14',
  'Total stats': '1806',
  'Base stats': '392',
  'International reputation': '1',
  'Pace / Diving': '62',
  'Shooting / Handling': '56',
  'Passing / Kicking': '66',
  'Dribbling / Reflexes': '67',
  'Defending / Pace': '67'},
 {'name': '20\xa0E. Belözoğlu CM\nCDM',
  'Age': '38',
  'Overall rating': '77',
  'Potential': '77',
  'Team & Contract': 'Fenerbahçe SK\n2019 ~ 2020',
  'ID': '80',
  'Height': '169cm 5\'7"',
  'Weight': '72kg 159lbs',
  'foot': 'Left',
  'Best overall': '77',
  'Best position': 'CM',
  'Growth': '0',
  'Value': '€2.2M',
  'Wage': '€44K',
  'Release clause': '€5.3M',
  'Total attacking': '342',
  'Crossing': '80',
  'Finishing': '66',
  'Heading accuracy': '43',
  'Short passing': '84',
  'Volleys': '69',
  'Total skill': '406',
  'Dribbling': '77',
  'Curve': '83',
  'FK Accuracy': '80',
  'Long passing': '85',
  'Ball control': '81',
  'Total movement': '308',
  'Acceleration': '54',
  'Sprint speed': '36',
  'Agility': '67',
  'Reactions': '70',
  'Balance': '81',
  'Total power': '340',
  'Shot power': '77',
  'Jumping': '72',
  'Stamina': '51',
  'Strength': '64',
  'Long shots': '76',
  'Total mentality': '384',
  'Aggression': '87',
  'Interceptions': '62',
  'Attack position': '65',
  'Vision': '85',
  'Penalties': '85',
  'Composure': '80',
  'Total defending': '190',
  'Defensive awareness': '65',
  'Standing tackle': '65',
  'Sliding tackle': '60',
  'Total goalkeeping': '47',
  'GK Diving': '7',
  'GK Handling': '11',
  'GK Kicking': '7',
  'GK Positioning': '14',
  'GK Reflexes': '8',
  'Total stats': '2017',
  'Base stats': '403',
  'International reputation': '2',
  'Pace / Diving': '44',
  'Shooting / Handling': '71',
  'Passing / Kicking': '83',
  'Dribbling / Reflexes': '77',
  'Defending / Pace': '62'},
 {'name': 'K. Alajbegović  CAM\nLM\nST',
  'Age': '17',
  'Overall rating': '68',
  'Potential': '83',
  'Team & Contract': 'FC Red Bull Salzburg\n2025 ~ 2029',
  'ID': '75533',
  'Height': '186cm 6\'1"',
  'Weight': '75kg 165lbs',
  'foot': 'Right',
  'Best overall': '70',
  'Best position': 'CAM',
  'Growth': '15',
  'Value': '€2.8M',
  'Wage': '€5K',
  'Release clause': '€6M',
  'Total attacking': '312',
  'Crossing': '64',
  'Finishing': '68',
  'Heading accuracy': '45',
  'Short passing': '67',
  'Volleys': '68',
  'Total skill': '347',
  'Dribbling': '72',
  'Curve': '72',
  'FK Accuracy': '68',
  'Long passing': '64',
  'Ball control': '71',
  'Total movement': '355',
  'Acceleration': '69',
  'Sprint speed': '70',
  'Agility': '74',
  'Reactions': '61',
  'Balance': '81',
  'Total power': '324',
  'Shot power': '76',
  'Jumping': '57',
  'Stamina': '60',
  'Strength': '56',
  'Long shots': '75',
  'Total mentality': '281',
  'Aggression': '59',
  'Interceptions': '33',
  'Attack position': '67',
  'Vision': '66',
  'Penalties': '56',
  'Composure': '59',
  'Total defending': '118',
  'Defensive awareness': '40',
  'Standing tackle': '41',
  'Sliding tackle': '37',
  'Total goalkeeping': '53',
  'GK Diving': '8',
  'GK Handling': '10',
  'GK Kicking': '8',
  'GK Positioning': '14',
  'GK Reflexes': '13',
  'Total stats': '1790',
  'Base stats': '374',
  'International reputation': '1',
  'Pace / Diving': '70',
  'Shooting / Handling': '70',
  'Passing / Kicking': '66',
  'Dribbling / Reflexes': '71',
  'Defending / Pace': '39'},
 {'name': 'K. Karetsas  CAM\nRW\nCM',
  'Age': '17',
  'Overall rating': '74',
  'Potential': '86',
  'Team & Contract': 'KRC Genk\n2024 ~ 2029',
  'ID': '70497',
  'Height': '171cm 5\'7"',
  'Weight': '62kg 137lbs',
  'foot': 'Left',
  'Best overall': '76',
  'Best position': 'CAM',
  'Growth': '12',
  'Value': '€9.5M',
  'Wage': '€12K',
  'Release clause': '€16.2M',
  'Total attacking': '303',
  'Crossing': '69',
  'Finishing': '70',
  'Heading accuracy': '26',
  'Short passing': '76',
  'Volleys': '62',
  'Total skill': '381',
  'Dribbling': '80',
  'Curve': '79',
  'FK Accuracy': '70',
  'Long passing': '72',
  'Ball control': '80',
  'Total movement': '389',
  'Acceleration': '85',
  'Sprint speed': '69',
  'Agility': '88',
  'Reactions': '58',
  'Balance': '89',
  'Total power': '312',
  'Shot power': '71',
  'Jumping': '53',
  'Stamina': '66',
  'Strength': '49',
  'Long shots': '73',
  'Total mentality': '242',
  'Aggression': '28',
  'Interceptions': '21',
  'Attack position': '63',
  'Vision': '75',
  'Penalties': '55',
  'Composure': '71',
  'Total defending': '72',
  'Defensive awareness': '18',
  'Standing tackle': '31',
  'Sliding tackle': '23',
  'Total goalkeeping': '49',
  'GK Diving': '11',
  'GK Handling': '12',
  'GK Kicking': '11',
  'GK Positioning': '6',
  'GK Reflexes': '9',
  'Total stats': '1748',
  'Base stats': '372',
  'International reputation': '1',

In [26]:
df = pd.DataFrame(players)

In [27]:
df

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,...,GK Positioning,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace
0,M. Amondarain CM\nCDM,20,72,81,Estudiantes de La Plata\n2025 ~ 2027,74813,"185cm 6'1""",75kg 165lbs,Right,74,...,13,6,1936,420,1,74,65,69,72,68
1,C. Tzolis LM\nLW,23,81,87,Club Brugge KV\n2024 ~ 2029,256948,"179cm 5'10""",73kg 161lbs,Right,82,...,6,10,2038,429,1,82,78,77,83,38
2,R. Ngumoha LM\nLW,16,72,88,Liverpool\n2025 ~ 2028,80376,"170cm 5'7""",68kg 150lbs,Right,73,...,9,12,1773,385,1,90,66,64,77,35
3,K. Adeyemi RM\nLW\nCAM\nRW,23,82,86,Borussia Dortmund\n2022 ~ 2027,251852,"180cm 5'11""",77kg 170lbs,Left,84,...,12,7,2052,435,3,96,80,72,82,36
4,G. Mora CAM\nLW\nCM,16,73,87,Mexico\nFree,79399,"168cm 5'6""",65kg 143lbs,Right,75,...,9,9,1791,377,1,67,65,73,74,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10075,23 B. Albizo ST,19,58,68,Caracas FC\n2022 ~ 2024,269718,"170cm 5'7""",58kg 128lbs,Right,61,...,6,11,1436,305,1,71,59,52,60,20
10076,S. Hidalgo RW\nRM\nST,20,70,81,Toulouse FC\n2025 ~ 2029,269719,"175cm 5'9""",71kg 157lbs,Left,72,...,5,9,1806,387,1,77,68,66,73,35
10077,25 E. N'Jo CB,20,59+1,71+1,ESTAC Troyes\n2022 ~ 2025,269724,"195cm 6'5""",80kg 176lbs,Right,61,...,8,6,1356,290,1,56,31,40,42,61
10078,L. Mouton CAM\nCM,23,72,79,Angers SCO\n2025 ~ 2028,269725,"180cm 5'11""",75kg 165lbs,Right,75,...,10,13,1838,401,1,69,53,69,76,61
10079,A. Aiki RM\nLM\nCAM\nRW,20,62,71,Sporting Club Bastia\n2025 ~ 2029,269726,"178cm 5'10""",75kg 165lbs,Right,64,...,11,13,1514,329,1,70,58,54,67,25

In [28]:
with pd.option_context('display.max_columns', None, 'display.max_rows', 5):
    display(df.head(5))
    display(df.describe(include='all'))

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,Best position,Growth,Value,Wage,Release clause,Total attacking,Crossing,Finishing,Heading accuracy,Short passing,Volleys,Total skill,Dribbling,Curve,FK Accuracy,Long passing,Ball control,Total movement,Acceleration,Sprint speed,Agility,Reactions,Balance,Total power,Shot power,Jumping,Stamina,Strength,Long shots,Total mentality,Aggression,Interceptions,Attack position,Vision,Penalties,Composure,Total defending,Defensive awareness,Standing tackle,Sliding tackle,Total goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace
0,M. Amondarain CM\nCDM,20,72,81,Estudiantes de La Plata\n2025 ~ 2027,74813,"185cm 6'1""",75kg 165lbs,Right,74,CM,9,€5M,€9K,€8.5M,320,66,65,63,75,51,325,72,55,51,73,74,353,73,74,71,70,65,354,67,73,80,67,67,329,73,69,66,68,53,72,205,67,69,69,50,14,10,7,13,6,1936,420,1,74,65,69,72,68
1,C. Tzolis LM\nLW,23,81,87,Club Brugge KV\n2024 ~ 2029,256948,"179cm 5'10""",73kg 161lbs,Right,82,CAM,6,€40.5M,€36K,€68.9M,378,75,80,68,79,76,381,84,75,66,75,81,410,85,79,84,77,85,382,79,78,85,63,77,324,70,29,79,78,68,79,110,33,39,38,53,15,10,12,6,10,2038,429,1,82,78,77,83,38
2,R. Ngumoha LM\nLW,16,72,88,Liverpool\n2025 ~ 2028,80376,"170cm 5'7""",68kg 150lbs,Right,73,CAM,16,€6M,€29K,€14.9M,293,68,66,38,64,57,326,78,69,52,53,74,419,92,89,85,65,88,314,73,61,62,54,64,271,39,36,66,71,59,74,101,32,39,30,49,11,9,8,9,12,1773,385,1,90,66,64,77,35
3,K. Adeyemi RM\nLW\nCAM\nRW,23,82,86,Borussia Dortmund\n2022 ~ 2027,251852,"180cm 5'11""",77kg 170lbs,Left,84,ST,4,€43.5M,€52K,€77.2M,374,73,81,75,74,71,364,84,69,62,69,80,441,96,96,86,82,81,399,86,93,77,67,76,316,59,31,82,74,70,76,108,25,34,49,50,12,12,7,12,7,2052,435,3,96,80,72,82,36
4,G. Mora CAM\nLW\nCM,16,73,87,Mexico\nFree,79399,"168cm 5'6""",65kg 143lbs,Right,75,CAM,14,€0,€0,€0,321,72,68,48,75,58,345,74,74,48,72,77,348,68,66,72,72,70,274,61,50,55,44,64,300,51,45,74,77,53,70,157,44,58,55,46,11,12,5,9,9,1791,377,1,67,65,73,74,50

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,Best position,Growth,Value,Wage,Release clause,Total attacking,Crossing,Finishing,Heading accuracy,Short passing,Volleys,Total skill,Dribbling,Curve,FK Accuracy,Long passing,Ball control,Total movement,Acceleration,Sprint speed,Agility,Reactions,Balance,Total power,Shot power,Jumping,Stamina,Strength,Long shots,Total mentality,Aggression,Interceptions,Attack position,Vision,Penalties,Composure,Total defending,Defensive awareness,Standing tackle,Sliding tackle,Total goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace
count,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080
unique,9339,28,118,131,6782,9346,50,51,2,48,15,27,252,133,1131,368,123,130,126,133,110,381,146,110,100,129,151,324,157,168,139,119,126,306,117,207,158,163,118,345,112,125,142,125,101,110,243,128,119,113,245,72,77,82,85,77,1354,258,5,71,75,68,66,75
top,Javi Rodríguez CB\nRB\nRM,20,62,70,Fortaleza\n2025 ~ 2028,203801,"180cm 5'11""",75kg 165lbs,Right,64,CB,0,€1.2M,€2K,€0,255,58,58,55,65,48,288,65,42,40,60,64,326,68,68,70,62,70,318,60,68,65,68,60,243,58,62,60,58,48,58,194,60,66,60,51,9,10,10,8,8,1564,332,1,67,63,58,64,58
freq,3,1195,519,612,21,3,834,898,7602,529,1956,2117,291,1200,1112,87,297,261,320,396,275,82,361,260,339,331,392,102,443,452,340,454,368,91,330,342,382,349,276,96,327,253,308,318,327,353,98,249,279,275,535,952,953,933,957,929,26,102,9296,449,319,384,437,254

In [29]:
df.describe()

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,...,GK Positioning,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace
count,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080,...,10080,10080,10080,10080,10080,10080,10080,10080,10080,10080
unique,9339,28,118,131,6782,9346,50,51,2,48,...,85,77,1354,258,5,71,75,68,66,75
top,Javi Rodríguez CB\nRB\nRM,20,62,70,Fortaleza\n2025 ~ 2028,203801,"180cm 5'11""",75kg 165lbs,Right,64,...,8,8,1564,332,1,67,63,58,64,58
freq,3,1195,519,612,21,3,834,898,7602,529,...,957,929,26,102,9296,449,319,384,437,254

In [30]:
df.to_csv('players_data.csv', index=False)